"""Add comprehensive analysis fields to DeepSearchCache

Revision ID: 2b776bb71cd7
Revises: 
Create Date: 2025-09-09 18:20:41.760445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b776bb71cd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deep_search_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_quality_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('values_alignment_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('engagement_potential_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brand_safety_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cultural_fit_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('influence_potential_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content_consistency_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('audience_quality_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('overall_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('analysis_reasoning', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recommendations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('risk_factors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('strengths', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('analysis_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deep_search_cache', schema=None) as batch_op:
        batch_op.drop_column('analysis_timestamp')
        batch_op.drop_column('strengths')
        batch_op.drop_column('risk_factors')
        batch_op.drop_column('recommendations')
        batch_op.drop_column('analysis_reasoning')
        batch_op.drop_column('overall_score')
        batch_op.drop_column('audience_quality_score')
        batch_op.drop_column('content_consistency_score')
        batch_op.drop_column('influence_potential_score')
        batch_op.drop_column('cultural_fit_score')
        batch_op.drop_column('brand_safety_score')
        batch_op.drop_column('engagement_potential_score')
        batch_op.drop_column('values_alignment_score')
        batch_op.drop_column('content_quality_score')

    # ### end Alembic commands ###
